version: '3.1'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html/:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    tty: true
    stdin_open: true
    networks:
      - main-network

  # postgres:
  #   container_name: postgresql
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres/data/:/var/lib/postgresql/data
  #     - ./postgres/scripts/:/docker-entrypoint-initdb.d/     
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: postgres
  #   networks:
  #     - main-network
    
  mysql:
    container_name: mysql
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/     
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - main-network

networks:
    main-network:
        driver: bridge