version: '3.1'
services:
  php-mysql:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html/:/var/www/html
    ports:
      - "8080:80"
    extra_hosts: 
      - "localhost:192.168.x.x" # Put your Ipv4 !!!
    depends_on:
      - mysql
    tty: true
    stdin_open: true
    networks:
      - main-network
    
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/     
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: root
    networks:
      - main-network

networks:
  main-network:
        driver: bridge